### ISSUE TITLE
[Bug]: Unusable with many components

### ISSUE THREAD

**Issue by Phhere** [Status-Page/Status-Page#507] opened 2023-03-29 08:57 UTC
### Description of the Bug

We added 140 components with the api and now the website is not useable any more.

https://status.test.hhu.de/

I think the many small bars for incidents cause an issue

### Expected behavior

Website should work normally

### Reproduction

1. Go to Backend and create many components in some component groups
2. Go to website
4. See error: Page is not loading 

### Version

> 2.0.0 (Preview)

### Information about your Device

**Desktop (please complete the following information):**
 - OS:  ArchLinux
 - Browser: Firefox
 - Version: 111.0.1

**Comment by HerrTxbias** [comment] 2023-03-29 14:28
I think I need to find a better / more performant solution there. Currently the only way to fix this is to make an update to all components that disables the historical display for them until I find a more performant solution.

**Comment by Phhere** [comment] 2023-03-29 15:20
Is the issue related to too many database queries or to render the historical data?

Maybe it is possible to generate an svg image for the historical display? Or maybe a jpeg with a image map could also be more performant.

**Comment by HerrTxbias** [comment] 2023-03-29 15:42
The Issue is related to too many database queries, yes.

I've created the branch `debug/optimized-component-history` with a possible fix for this issue. Would you test if the Overview loads again on this branch?

**Comment by Phhere** [comment] 2023-04-25 08:58
It is still unusable. Do you have any further idea? we really would like to use it for our university in Düsseldorf

**Comment by HerrTxbias** [comment] 2023-04-29 23:43
I've created another branch, where i'm using SVGs to display the historic status: `fix/svgs-for-historic-status`. Could you check it out and give me a short feedback on this?

**Comment by Phhere** [comment] 2023-05-02 07:46
There is an issue during upgrade.sh

```
Applying database migrations (python3 statuspage/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/status-page/statuspage/manage.py", line 22, in <module>
    main()
  File "/opt/status-page/statuspage/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/status-page/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/status-page/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/status-page/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/status-page/venv/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/opt/status-page/statuspage/queuing/apps.py", line 15, in ready
    scheduler = django_rq.get_scheduler('default')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/status-page/venv/lib/python3.11/site-packages/django_rq/queues.py", line 307, in get_scheduler
    raise ImproperlyConfigured('rq_scheduler not installed')
django.core.exceptions.ImproperlyConfigured: rq_scheduler not installed

**Comment by HerrTxbias** [comment] 2023-05-02 20:58
This import issue has been fixed. I've rebased the branch so you can test the SVG changes now.

**Comment by Phhere** [comment] 2023-05-03 07:40
Thanks. 
pysvg seems to be missing in requirements.txt
```
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'utilities.templatetags.helpers': No module named 'pysvg'

``` 

I added pysvg-py3 to requirements.txt and now it works quiet well
https://status.test.hhu.de/

**Closed** 2023-05-03 09:20 UTC
Labels: bug, severity: high, scope: components
